WIP - Add tests for the project
krossroad/laravel-unionpaginator pull request #11
Opened 2018-10-08 02:37 UTC by samundra

@krossroad,

I am writing unit test for the project and currently I am stucked. Since during the test I am not using the real database and mocking the connection. Also, we might need to refactor some of the codes.

So far, with current changes, This is the failed output that I am able to get from the tests.

```
PHPUnit 7.4-gbe6564ea4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 146 ms, Memory: 6.00MB

There was 1 error:

1) Tests\Unit\Krossroad\UnionPaginator\UnionAwareBuilderTest\UnionAwareBuilderTest::testUnionPaginateReturnsLengthAwarePaginator
LogicException: Lost connection and no reconnector available.

/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Connection.php:757
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Connection.php:768
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Connection.php:616
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Connection.php:333
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Query/Builder.php:2027
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Query/Builder.php:2015
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Query/Builder.php:2499
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Query/Builder.php:2016
/Users/samundra/personal/www/laravel-unionpaginator/vendor/illuminate/database/Concerns/BuildsQueries.php:77
/Users/samundra/personal/www/laravel-unionpaginator/src/UnionAwareBuilder.php:64
/Users/samundra/personal/www/laravel-unionpaginator/src/UnionAwareBuilder.php:28
/Users/samundra/personal/www/laravel-unionpaginator/tests/Unit/Krossroad/UnionPaginator/UnionAwareBuilderTest.php:98

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

How would you suggest to make the test for it?

2018-10-08 17:24 UTC, krossroad requested changes

2018-10-08 17:42 UTC, samundra commented on tests/Unit/TestCase.php
> +    protected function callMethod($object, string $methodName, array $args = [])
Let me test this. If not needed I will remove it.

2018-10-08 17:49 UTC, samundra commented
@krossroad Removed redundant code. Tested and works fine.

2018-10-09 01:56 UTC, samundra commented
@krossroad I have added `.travis.yml` config as well. For now, it's not doing much. It only runs the phpunit. Please verify. Thanks.

2021-08-16 06:40 UTC, closed without merging